app_bundle_job:
    resource: '@AppBundle/Resources/config/routing/job.yml'
    prefix: /job

app_bundle_category:
    resource: '@AppBundle/Resources/config/routing/category.yml'
    prefix: /category